// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/stockfish.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class StockfishBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  StockfishBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  StockfishBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int stockfish_main() {
    return _stockfish_main();
  }

  late final _stockfish_mainPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('stockfish_main');
  late final _stockfish_main = _stockfish_mainPtr.asFunction<int Function()>();

  int stockfish_write(
    ffi.Pointer<ffi.Char> s,
  ) {
    return _stockfish_write(
      s,
    );
  }

  late final _stockfish_writePtr =
      _lookup<ffi.NativeFunction<ssize_t Function(ffi.Pointer<ffi.Char>)>>(
          'stockfish_write');
  late final _stockfish_write =
      _stockfish_writePtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> stockfish_read(
    ffi.Pointer<ffi.Char> s,
  ) {
    return _stockfish_read(
      s,
    );
  }

  late final _stockfish_readPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>)>>('stockfish_read');
  late final _stockfish_read = _stockfish_readPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();
}

typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef ssize_t = __darwin_ssize_t;
